version: '3.4'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
      - /etc/ssl/public:/etc/ssl/public
      - /etc/ssl/priv:/etc/ssl/priv
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=chuc
      - DOCKER_INFLUXDB_INIT_PASSWORD=u#9rpG4DUdMT*##+uHC2FeBC#KP
      - DOCKER_INFLUXDB_INIT_ORG=iot.brilliant-care.pl
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket
      - INFLUXD_TLS_CERT=/etc/ssl/public
      - INFLUXD_TLS_KEY=/etc/ssl/priv

volumes:
    influxdb-storage:
